# Generated by Django 4.1.7 on 2023-03-26 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_cuentacobrar_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacobrarcuota',
            name='cuenta_cobrar',
        ),
        migrations.RemoveField(
            model_name='cuentacobrarpago',
            name='cuenta_cobrar_cuota',
        ),
        migrations.DeleteModel(
            name='CuentaCobrar',
        ),
        migrations.DeleteModel(
            name='CuentaCobrarCuota',
        ),
        migrations.DeleteModel(
            name='CuentaCobrarPago',
        ),
    ]
