# Generated by Django 4.1.7 on 2023-03-26 02:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0004_remove_cuentacobrarcuota_cuenta_cobrar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_credito', models.DateField(default=django.utils.timezone.now)),
                ('credito', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='credito')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('numero_pagos', models.IntegerField(default=3)),
                ('cuota', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha_primer_pago', models.DateField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Pagado')], default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
            },
        ),
        migrations.CreateModel(
            name='CuentaCobrarCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pagar', models.DateField(blank=True, null=True, verbose_name='Fecha Pagar')),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Couta')),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Pagado')], default=0)),
                ('cuenta_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.cuentacobrar')),
            ],
            options={
                'verbose_name': 'Cuenta x Cobrar detalle',
                'verbose_name_plural': 'Cuentas x Cobrar detalle',
            },
        ),
        migrations.CreateModel(
            name='CuentaCobrarPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Pago')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('cuenta_cobrar_cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.cuentacobrarcuota')),
            ],
            options={
                'verbose_name': 'Cuenta x Cobrar Pago',
                'verbose_name_plural': 'Cuentas x Cobrar Pago',
            },
        ),
    ]
