# Generated by Django 4.1.7 on 2023-03-27 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_remove_cuentacobrarcuota_cuenta_cobrar_and_more'),
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacobrar',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cliente'),
        ),
        migrations.AlterField(
            model_name='cuentacobrar',
            name='estado',
            field=models.CharField(choices=[('PA', 'Pagado'), ('PE', 'Pediente')], default='PA', max_length=2),
        ),
        migrations.AlterField(
            model_name='cuentacobrarcuota',
            name='cuenta_cobrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobros.cuentacobrar'),
        ),
        migrations.AlterField(
            model_name='cuentacobrarpago',
            name='cuenta_cobrar_cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobros.cuentacobrarcuota'),
        ),
    ]
